//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReferenceForTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceForTest.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadPath", ReplyAction="*")]
        ConsoleApp1.ServiceReferenceForTest.ReadPathResponse ReadPath(ConsoleApp1.ServiceReferenceForTest.ReadPathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadPath", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReferenceForTest.ReadPathResponse> ReadPathAsync(ConsoleApp1.ServiceReferenceForTest.ReadPathRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadPathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadPath", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReferenceForTest.ReadPathRequestBody Body;
        
        public ReadPathRequest() {
        }
        
        public ReadPathRequest(ConsoleApp1.ServiceReferenceForTest.ReadPathRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadPathRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public ReadPathRequestBody() {
        }
        
        public ReadPathRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadPathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadPathResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ServiceReferenceForTest.ReadPathResponseBody Body;
        
        public ReadPathResponse() {
        }
        
        public ReadPathResponse(ConsoleApp1.ServiceReferenceForTest.ReadPathResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadPathResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReadPathResult;
        
        public ReadPathResponseBody() {
        }
        
        public ReadPathResponseBody(string ReadPathResult) {
            this.ReadPathResult = ReadPathResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsoleApp1.ServiceReferenceForTest.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReferenceForTest.WebService1Soap>, ConsoleApp1.ServiceReferenceForTest.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ServiceReferenceForTest.ReadPathResponse ConsoleApp1.ServiceReferenceForTest.WebService1Soap.ReadPath(ConsoleApp1.ServiceReferenceForTest.ReadPathRequest request) {
            return base.Channel.ReadPath(request);
        }
        
        public string ReadPath(string fileName) {
            ConsoleApp1.ServiceReferenceForTest.ReadPathRequest inValue = new ConsoleApp1.ServiceReferenceForTest.ReadPathRequest();
            inValue.Body = new ConsoleApp1.ServiceReferenceForTest.ReadPathRequestBody();
            inValue.Body.fileName = fileName;
            ConsoleApp1.ServiceReferenceForTest.ReadPathResponse retVal = ((ConsoleApp1.ServiceReferenceForTest.WebService1Soap)(this)).ReadPath(inValue);
            return retVal.Body.ReadPathResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ServiceReferenceForTest.ReadPathResponse> ConsoleApp1.ServiceReferenceForTest.WebService1Soap.ReadPathAsync(ConsoleApp1.ServiceReferenceForTest.ReadPathRequest request) {
            return base.Channel.ReadPathAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ServiceReferenceForTest.ReadPathResponse> ReadPathAsync(string fileName) {
            ConsoleApp1.ServiceReferenceForTest.ReadPathRequest inValue = new ConsoleApp1.ServiceReferenceForTest.ReadPathRequest();
            inValue.Body = new ConsoleApp1.ServiceReferenceForTest.ReadPathRequestBody();
            inValue.Body.fileName = fileName;
            return ((ConsoleApp1.ServiceReferenceForTest.WebService1Soap)(this)).ReadPathAsync(inValue);
        }
    }
}
