//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployedWindowsClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadPath", ReplyAction="*")]
        EmployedWindowsClient.ServiceReference1.ReadPathResponse ReadPath(EmployedWindowsClient.ServiceReference1.ReadPathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadPath", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployedWindowsClient.ServiceReference1.ReadPathResponse> ReadPathAsync(EmployedWindowsClient.ServiceReference1.ReadPathRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadPathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadPath", Namespace="http://tempuri.org/", Order=0)]
        public EmployedWindowsClient.ServiceReference1.ReadPathRequestBody Body;
        
        public ReadPathRequest() {
        }
        
        public ReadPathRequest(EmployedWindowsClient.ServiceReference1.ReadPathRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadPathRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public ReadPathRequestBody() {
        }
        
        public ReadPathRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadPathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadPathResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployedWindowsClient.ServiceReference1.ReadPathResponseBody Body;
        
        public ReadPathResponse() {
        }
        
        public ReadPathResponse(EmployedWindowsClient.ServiceReference1.ReadPathResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadPathResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReadPathResult;
        
        public ReadPathResponseBody() {
        }
        
        public ReadPathResponseBody(string ReadPathResult) {
            this.ReadPathResult = ReadPathResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : EmployedWindowsClient.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<EmployedWindowsClient.ServiceReference1.WebService1Soap>, EmployedWindowsClient.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployedWindowsClient.ServiceReference1.ReadPathResponse EmployedWindowsClient.ServiceReference1.WebService1Soap.ReadPath(EmployedWindowsClient.ServiceReference1.ReadPathRequest request) {
            return base.Channel.ReadPath(request);
        }
        
        public string ReadPath(string fileName) {
            EmployedWindowsClient.ServiceReference1.ReadPathRequest inValue = new EmployedWindowsClient.ServiceReference1.ReadPathRequest();
            inValue.Body = new EmployedWindowsClient.ServiceReference1.ReadPathRequestBody();
            inValue.Body.fileName = fileName;
            EmployedWindowsClient.ServiceReference1.ReadPathResponse retVal = ((EmployedWindowsClient.ServiceReference1.WebService1Soap)(this)).ReadPath(inValue);
            return retVal.Body.ReadPathResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployedWindowsClient.ServiceReference1.ReadPathResponse> EmployedWindowsClient.ServiceReference1.WebService1Soap.ReadPathAsync(EmployedWindowsClient.ServiceReference1.ReadPathRequest request) {
            return base.Channel.ReadPathAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployedWindowsClient.ServiceReference1.ReadPathResponse> ReadPathAsync(string fileName) {
            EmployedWindowsClient.ServiceReference1.ReadPathRequest inValue = new EmployedWindowsClient.ServiceReference1.ReadPathRequest();
            inValue.Body = new EmployedWindowsClient.ServiceReference1.ReadPathRequestBody();
            inValue.Body.fileName = fileName;
            return ((EmployedWindowsClient.ServiceReference1.WebService1Soap)(this)).ReadPathAsync(inValue);
        }
    }
}
